apiVersion: v1
kind: Service
metadata:
  name: {{ include "pesitwizard-client.fullname" . }}-api
  labels:
    {{- include "pesitwizard-client.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pesitwizard-client.api.selectorLabels" . | nindent 4 }}
